---
title: "DAG"
format: pdf
editor: visual
---


```{r}
# Instalar y cargar librerías
library(bnlearn)
library(readr)

```

```{r}
set.seed(1234)
data = read_csv("~/Desktop/Repositorio/Datos Finales/Data/data_corregido.csv")
```
```{r}
data$S   <- factor(data$S)     # sexo
data$A   <- factor(data$A)     # edad_cat
data$EST <- factor(data$EST)   # estrato
data$T   <- factor(data$T)     # transporte
data$D   <- factor(data$D)     # dia_viaje
data$O   <- factor(data$O)     # entidad
data$L   <- factor(data$L)     # localidad
data$H   <- factor(data$H)     # tiempo_cat
data$V   <- factor(data$V)     # autos_camionetas
data$ESC <- factor(data$ESC)   # escolaridad
```

```{r}
sapply(data[, c("A","D","EST","V","L","H","O","ESC","S","T")], class)
```

```{r}
dag_hc = hc(df)
```

```{r}
modelstring(dag_hc)
```

```{r}
graphviz.plot(dag_hc, shape = "rectangle")
```

```{r}
head(data)
```

```{r}
bn = bn.fit(dag_hc,data=data)
```

```{r}
cpquery(
  bn,
  event    = (O == "1"),
  evidence = (T == "taxi" & EST == c("2")),
  method   = "lw",      
  n        = 10^6      
)
```











